pipeline {

    agent {
        node {
            label 'slave_1'
        }
    }

    tools {
        maven 'MAVEN_HOME'
        jdk 'JAVA_HOME'
    }

    parameters {
        choice(
            name: 'Env_Name',
            choices: ['DEV', 'PROD'],
            description: 'Select deployment environment'
        )
    }

    stages {

        stage('Pre-Build') {
            steps {
                echo 'Starting CI/CD Pipeline'
            }
        }

        stage('Git Checkout') {
            steps {
                checkout([
                    $class: 'GitSCM',
                    branches: [[name: '*/master']],
                    extensions: [],
                    userRemoteConfigs: [[
                        credentialsId: '',
                        url: 'https://github.com/devopscloudtrainer25/Project-Management.git'
                    ]]
                ])
            }
        }

        stage('Build') {
            steps {
                sh '''
                    mvn clean package -DskipTests
                '''
            }
        }

        stage('Unit Test') {
            steps {
                echo 'Running Unit Tests'

                sh '''
                    mvn test
                '''
            }
        }

        stage('Install to Local Repository') {
            steps {
                sh '''
                    mvn install -DskipTests
                '''
            }
        }

        stage('Static Code Analysis') {
            environment {
                scannerHome = tool 'SONAR_SCANNER'
            }

            steps {
                echo 'Running SonarQube Analysis'

                withSonarQubeEnv('SONAR_HOME') {
                    sh '''
                        ${scannerHome}/bin/sonar-scanner
                    '''
                }
            }
        }

        stage('Upload Artifact to JFrog') {
            steps {

                rtUpload(
                    serverId: 'artifactory',

                    spec: '''{
                        "files": [
                            {
                                "pattern": "target/*.war",
                                "target": "local-snapshot-repo/"
                            }
                        ]
                    }'''
                )
            }
        }

        stage('Deploy using Ansible') {

            steps {

                script {

                    if (params.Env_Name == 'DEV') {

                        echo 'Deploying application to DEV environment'

                        sh '''
                            ansible-playbook \
                            -i /var/lib/jenkins/inventory \
                            Project/Ansible/webserver-1-tomcat.yml \
                            -vv
                        '''

                    } else if (params.Env_Name == 'PROD') {

                        echo 'Deploying application to PROD environment'

                        sh '''
                            ansible-playbook \
                            -i /var/lib/jenkins/inventory \
                            Project/Ansible/webserver-2-tomcat.yml \
                            -vv
                        '''
                    }
                }
            }
        }

        stage('Post-Build') {
            steps {
                echo 'Successful Pipeline'
            }
        }
    }

    post {

        success {
            echo 'CI/CD Pipeline completed successfully'
        }

        failure {
            echo 'CI/CD Pipeline failed'
        }
    }
}
