pipeline {
    agent {
        node {
            label 'slave_1'
        }
    }

    tools {
        maven 'MAVEN_HOME'
        jdk 'JAVA_HOME'
        git 'GIT_HOME'
    }

    stages {

        stage('Pre Build Step') {
            steps {
                echo 'Starting CI/CD Pipeline'
            }
        }

        stage('Git Checkout') {
            steps {
                checkout([
                    $class: 'GitSCM',
                    branches: [[name: '*/master']],
                    extensions: [],
                    userRemoteConfigs: [[
                        url: 'https://github.com/aman9515/Project-Management.git'
                    ]]
                ])
            }
        }

        stage('Build') {
            steps {
                sh 'mvn clean package'
            }
        }

        stage('Unit Test') {
            steps {
                echo 'Running Unit Tests'
                sh 'mvn test'
            }
        }

        stage('Maven Install') {
            steps {
                sh 'mvn install'
            }
        }

        stage('Static Code Analysis') {
            environment {
                scannerHome = tool 'SONAR_SCANNER'
            }

            steps {
                echo 'Running SonarQube Static Code Analysis'

                withCredentials([
                    string(
                        credentialsId: 'sonar-token',
                        variable: 'SONAR_TOKEN'
                    )
                ]) {
                    sh '''
                        ${scannerHome}/bin/sonar-scanner \
                        -Dsonar.host.url=http://54.79.18.48:8080 \
                        -Dsonar.projectKey=roshan:project \
                        -Dsonar.projectName=roshan-project \
                        -Dsonar.projectVersion=1.0 \
                        -Dsonar.sources=src/main \
                        -Dsonar.tests=src/test \
                        -Dsonar.java.binaries=target/classes \
                        -Dsonar.sourceEncoding=UTF-8 \
                        -Dsonar.token=$SONAR_TOKEN
                    '''
                }
            }
        }

        stage('JFrog Artifact Upload') {
            steps {
                echo 'Uploading WAR file to JFrog Artifactory'

                withCredentials([
                    usernamePassword(
                        credentialsId: 'jfrog-credentials',
                        usernameVariable: 'JFROG_USER',
                        passwordVariable: 'JFROG_PASSWORD'
                    )
                ]) {
                    sh '''
                        curl -u "$JFROG_USER:$JFROG_PASSWORD" \
                        -T target/simple-maven-project.war \
                        "http://3.25.218.220:8082/artifactory/local-snapshot-repo/simple-maven-project.war"
                    '''
                }
            }
        }

        stage('Tomcat Deployment') {
            steps {
                echo 'Deploying WAR file to Tomcat'

                deploy adapters: [
                    tomcat9(
                        credentialsId: 'tomcat-key',
                        path: '',
                        url: 'http://3.25.218.220'
                    )
                ],
                contextPath: '/ecommerce',
                onFailure: false,
                war: 'target/simple-maven-project.war'
            }
        }

        stage('Post Build Step') {
            steps {
                echo 'Successfully completed CI/CD Pipeline'
            }
        }
    }
}
